### ISSUE TITLE
'encoding' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by dymoksc** [jmriebold/chat-stats#1]
Hi, I've got a following error message:
`Traceback (most recent call last):`
`  File "chat-stats.py", line 232, in <module>`
`    names = get_participants(transcript)`
`  File "chat-stats.py", line 43, in get_participants`
`    with open(transcript, 'r', encoding='utf8') as in_file:`
`TypeError: 'encoding' is an invalid keyword argument for this function`

**Comment by jmriebold** [comment]
Ah, sounds like you're using Python 2. The encoding parameter for open() was introduced in Python 3. If you want to work around it and aren't worried about UTF-8, you can just remove any instances of "encoding='utf-8'".
